function goldpath1 = import_file_as_matrix(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  GOLDPATH1 = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  GOLDPATH1 = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  goldpath1 = importfile1("/Users/paawanjethva/Documents/Bachelor of Mathematical Sciences (Advanced)/Year 1/MCM/MCM Code/MCM/Trading Data/GBM Simulation/gold_path.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Feb-2022 23:19:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["present_day", "drift", "final_price", "future_day"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
goldpath1 = readtable(filename, opts);

%% Convert to output type
goldpath1 = table2array(goldpath1);
end